//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OlimpiadaForYou.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Olimp_Registration
    {
        public int ID { get; set; }
        public int ID_User { get; set; }
        public int ID_Olimp { get; set; }
        public Nullable<int> Result { get; set; }

        public string DisplayResult
        {
            get
            {
                return Result.HasValue ? Result.Value.ToString() : "Ещё не проставлено";
            }
        }

        public virtual Olimp_Olimp Olimp_Olimp { get; set; }
        public virtual Olimp_Users Olimp_Users { get; set; }
    }
}
